add smaller test model, refactor tests
r4ss/r4ss pull request #700
Opened 2022-06-24 22:45 UTC by iantaylor-NOAA

This Pull Request includes the following:
- adds a new "simple_small" model
  - based on "simple"
  - has fewer years (main time series is 2011-2022)
  - minor changes to model configuration for simplicity or to implement more common settings
  - files are about 2 MB which should be small enough to keep the package within the 5 MB limit on CRAN
  - changes from "simple" made via script attached to this comment https://github.com/r4ss/r4ss/issues/206#issuecomment-1157078047
- refactors the tests to put all tests associated with 3.24 and earlier 3.30 versions into a single `test-older_ss3.R` file which can be excluded from future CRAN submissions along with those model files
- other tests should work on CRAN with the exception of those that require the executable which will be skipped

I think this draft pull request will trigger a code coverage check which will help me see if I've missed some important pieces.
Feel free to comment on any of this.

2022-06-27 16:15 UTC, k-doering-NOAA commented
@iantaylor-NOAA, good call on making a smaller model. I think we should go ahead and replace any of the simple 3.30 models with this model!

I'm curious, do you think we should retain a 3.24 model for testing (even if that testing is skipped on CRAN)? And if so, should we try to make it smaller like this one?

2022-06-27 16:16 UTC, k-doering-NOAA commented
Also, I took a brief glance through the diffs and the changes make sense to me. I haven't scrutinized everything line-by-line, though, as I figure I can do that when this is no longer a draft. Happy to take a closer look if you would like, though!

2022-06-27 17:40 UTC, iantaylor-NOAA commented
@k-doering-NOAA, good questions. I thought about removing the old models, but it doesn't make sense to maintain the read/write functions for 3.24 models if we don't maintain the tests that check those functions.

We had a discussion about backwards compatibility in #306 and I think this PR is in line with the views shared there: maintaining tools for accessing and understanding models associated with old versions of SS3 (`SS_output()`, `SS_plots()`, and the read/write functions for the input files), but no longer testing things like the profile, retrospective, or jitter functions for old versions.

However, it surely doesn't make sense to include the files associated with those older version as part of the package that all users get when installing r4ss from github. Would it be possible to create a new repo with the simple models from the older versions of SS3 and revise the r4ss-extra-tests workflow to copy them for testing purposes? That would also save us from removing those files from future CRAN submissions.

2022-07-06 16:33 UTC, k-doering-NOAA commented
@iantaylor-NOAA , should the simple_3.30.xx models in inst/extdata be removed before merging in, since the smaller test can serve as a replacement?

2022-07-06 16:35 UTC, k-doering-NOAA commented on tests/testthat/test-control.R
> -test_that("SS_readctl and SS_writectl works for 3.30.13", {
I think the other 3.30.xx version tests can be removed in this PR.

2022-07-06 16:40 UTC, k-doering-NOAA commented on tests/testthat/test_Sensi_plot.R
> +    current.year = 2022,
Good idea to make the last model year 2022 instead of 2001!

2022-07-06 16:42 UTC, k-doering-NOAA requested changes
Hi @iantaylor-NOAA , it looks good. I asked a few questions for you to consider. Once done with changes, I will change the workflows to reference `@main` instead .

2022-07-11 19:05 UTC, iantaylor-NOAA commented on tests/testthat/test-control.R
> -test_that("SS_readctl and SS_writectl works for 3.24 when datlist = FALSE", {
Tests removed as discussed in #702

2022-07-12 00:16 UTC, iantaylor-NOAA commented
After way to many typos and omissions, I think I've got these changes cleaned up and the suggestions from @k-doering-NOAA implemented and tests passing, so will merge this branch.

There remains cleanup to deprecate and then remove the 3.24-related functions in #702 but that can be separate and happen later. Also, we may still want to move the 3.24 model and earlier 3.30 models used for testing `SS_output()` into a different repo and create a new github action to use it for testing.

Code coverage has decreased because the read/write functions for 3.24 models aren't being tested, and some of the elements of `SS_output()` that are specific to earlier 3.30 versions are also being skipped. But I'm OK with all those reductions.

2022-07-12 00:16 UTC, merged

2022-07-12 16:46 UTC, k-doering-NOAA commented
Thanks @iantaylor-NOAA ! I can work on deprecating the 3.24 functions.