Add curl check for windows in get_ss3_exe()
r4ss/r4ss pull request #940
Opened 2024-05-29 17:51 UTC by e-perl-NOAA

See issue #927.

2024-05-29 17:53 UTC, e-perl-NOAA commented
@kellijohnson-NOAA does this look like a good fix to you?

2024-05-29 18:54 UTC, iantaylor-NOAA requested changes
@e-perl-NOAA, thanks for working on this so quickly.

I have two changes to suggest. First, I think the grepl should look for "OpenSSL" not "Schannel", because that will for sure confirm the presence/absence of the version that fixes the error for NOAA folks. The common Windows alternative is "Windows Secure Channel" (which could be theoretically abreviated "Schannel") but I can't figure out how to unset the OpenSSL setup to  figure out what the ssl_version looks like or to replicate the error when you have it set wrong.

Second, it's possible that someone would need to have a setting which isn't OpenSSL and that the function would work for them anyway (I just don't know enough about these settings to judge). So I would change `stop()` to `warning()` and add something like this to the top of the message to explain why you would want a change: 
`If this function returns "status was 'SSL connect error'", try changing the following settings:`

@kellijohnson-NOAA, I'm assuming you saw someone experience this error which inspired your comment yesterday https://github.com/r4ss/r4ss/issues/927#issuecomment-2135412436, so please feel free to suggest any changes to the above to better fit your vision for the fix.

2024-05-29 19:08 UTC, kellijohnson-NOAA commented on R/get_ss3_exe.r
> +        "4. Try remotes::install_github() (e.g., devtools::install_github('tidyverse/dplyr')). It should work and continue to work in future R sessions."
I am not sure why #4 is present?

2024-05-29 19:15 UTC, kellijohnson-NOAA commented
@iantaylor-NOAA that someone was me! And, I thought to myself "oh man now I have to find the issue with the fix, I wish the instructions were just right here" but I did feel lucky that I knew where to 👀.
@e-perl-NOAA it seems as though it would be better to only provide the instructions if the function fails rather than searching for something on someone's machine given we do not know all of the cases that could lead to the failure.

2024-05-29 19:58 UTC, iantaylor-NOAA commented
@kellijohnson-NOAA, if you take away the .Renviron file, does the error return? The hard part of writing the function to only produce the message when it errors is that we need the error to test it.

2024-05-29 20:06 UTC, kellijohnson-NOAA commented
```
> r4ss::get_ss3_exe(dir="c:/users/kelli.johnson/Downloads")
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe'
Error in utils::download.file(url, destfile = file.path(dir, "ss3.exe"),  : 
  cannot open URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe'
In addition: Warning message:
In utils::download.file(url, destfile = file.path(dir, "ss3.exe"),  :
  URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe': status was 'SSL connect error'
```

2024-05-29 20:28 UTC, iantaylor-NOAA commented
Great!
I can't make it come back.
We've already wrapped up `utils::download.file()` in `tryCatch()` and `suppressWarnings()`, and after playing with a few combinations of those things I can't figure out how to access the warning that gets returned by `utils::download.file()` within the function. Myabe simplest would be to just add a third step such that if it fails with "ss3" then it tries "ss" and if that also fails, then it checks the ss_version and produces the error if it's missing OpenSSL.

2024-05-29 21:08 UTC, e-perl-NOAA commented
@iantaylor-NOAA agreed and I don't get the error. Thank you Kelli for testing. I may need you to test it again once I get the changes through and working!

2024-05-30 14:19 UTC, kellijohnson-NOAA commented
I did some digging and `utils::download.file()` is using `.Internal()` which makes capturing the `stop()` difficult. But, you can capture it using the following code which I got from `demo(error.catching)`
```
tryCatch.W.E <- function(expr) {
    W <- NULL
    w.handler <- function(w) { # warning handler
      W <<- w
      invokeRestart("muffleWarning")
    }
    list(value = withCallingHandlers(tryCatch(expr, error = function(e) e),
                                   warning = w.handler),
       warning = W)
}

# Test out the function
test <- tryCatch.W.E(r4ss::get_ss3_exe(dir="c:/users/kelli.johnson/Downloads"))
> test
$value
<simpleError in utils::download.file(url, destfile = file.path(dir, "ss3.exe"),     mode = "wb"): cannot open URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe'>

$warning
<simpleWarning in utils::download.file(url, destfile = file.path(dir, "ss3.exe"),     mode = "wb"): URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe': status was 'SSL connect error'>
```

2024-05-30 15:32 UTC, e-perl-NOAA commented
@kellijohnson-NOAA I tried 2 different methods, one using the one you suggested (commit [5833c47](https://github.com/r4ss/r4ss/pull/940/commits/5833c47f1aa66b4fb15ae9cbef993ae195421b44)) and the other using a different method (commit [444c430](https://github.com/r4ss/r4ss/pull/940/commits/444c43090868d422912ba393bcbfbb4f5905f088)). Would you mind trying each of these commits to see which one works best or you like better? I have never had any OpenSSL errors on my machine so it's difficult for me to test.

2024-05-30 18:29 UTC, kellijohnson-NOAA commented
[5833c47](https://github.com/r4ss/r4ss/pull/940/commits/5833c47f1aa66b4fb15ae9cbef993ae195421b44) did not work for many reasons (1) loading the package to check the function did not work because there are two versions of the function in the R folder and the second file is used for `get_ss3_exe()` rather than the first (2) in the function there are some errors in the implementation, e.g., `try_ss` instead of `try_ss3` and `tryCatch.W.E.()` instead of `tryCatch.W.E()`. But, it appears that if you use what is returned from `tryCatch.W.E()` then things will work. 

[444c430](https://github.com/r4ss/r4ss/pull/940/commits/444c43090868d422912ba393bcbfbb4f5905f088) led to failure and the following
```
> r4ss::get_ss3_exe(dir="c:/users/kelli.johnson/Downloads")
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe'
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
Error in utils::download.file(url, destfile = file.path(dir, "ss3.exe"),  : 
  cannot open URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
In addition: Warning message:
In utils::download.file(url, destfile = file.path(dir, "ss3.exe"),  :
  URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe': status was 'SSL connect error'
```

2024-05-31 13:35 UTC, e-perl-NOAA commented
Okay I think that I fixed it. @kellijohnson-NOAA can you try the latest commit?

2024-05-31 13:44 UTC, kellijohnson-NOAA commented
@e-perl-NOAA it partially worked. If I pass any argument, whether it is a valid directory or not, to `dir` it results in an additional error message that may or may not be true. And, it is not intuitive to the user when it says `download_location` not found when the user does not pass anything to `download_location`. `dir` is the only object name that the user actually knows. Additionally, it is still not clear to me why element (4) is in the list of instructions.
```
> r4ss::get_ss3_exe(dir="c:/users/kelli.johnson/Downloads")
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe'
Error in r4ss::get_ss3_exe(dir = "c:/users/kelli.johnson/Downloads") : 
  object 'download_location' not found
In addition: Warning message:
In r4ss::get_ss3_exe(dir = "c:/users/kelli.johnson/Downloads") :
  Possible error with connect OpenSSL. Please do the following:
1. Run write('CURL_SSL_BACKEND=openssl', file = '~/.Renviron', append = TRUE) in your R session
2. Restart your R session
3. Run curl::curl_version()$ssl_version and confirm the return is OpenSSL/1.1.1 (Schannel) (note the numbers may be different)
4. Try remotes::install_github() (e.g., devtools::install_github('tidyverse/dplyr')). It should work and continue to work in future R sessions.
```

2024-05-31 14:23 UTC, e-perl-NOAA commented
Sorry, in trying to get things to work I forgot to remove that step. I pushed a different attempt to fix if you can try that out when you get a chance (given the windows check passes but it should because I ran the test on my machine).

2024-05-31 14:34 UTC, kellijohnson-NOAA commented
Now I get the following, even though nothing is downloaded.
```
> r4ss::get_ss3_exe(dir="c:/users/kelli.johnson/Downloads")
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe'
The stock synthesis executable for Windows v3.30.22.1 was downloaded to: c:/users/kelli.johnson/Downloads/ss3.exe
```

2024-05-31 14:59 UTC, e-perl-NOAA commented
Ugh, okay. Just pushed what might be my last attempt before I admit defeat and might need your assistance with this one @kellijohnson-NOAA . I really wish that I could produce the error locally.

2024-05-31 15:01 UTC, kellijohnson-NOAA commented
We are back to the previous version where there is an incorrect error about the download_location
```
> r4ss::get_ss3_exe(dir="c:/users/kelli.johnson/Downloads")
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe'
Error in r4ss::get_ss3_exe(dir = "c:/users/kelli.johnson/Downloads") : 
  object 'download_location' not found
In addition: Warning message:
In r4ss::get_ss3_exe(dir = "c:/users/kelli.johnson/Downloads") :
  Possible error with connect OpenSSL. Please do the following:
1. Run write('CURL_SSL_BACKEND=openssl', file = '~/.Renviron', append = TRUE) in your R session
2. Restart your R session
3. Run curl::curl_version()$ssl_version and confirm the return is OpenSSL/1.1.1 (Schannel) (note the numbers may be different)
```

2024-12-09 21:26 UTC, closed without merging

2024-12-09 21:26 UTC, iantaylor-NOAA commented
I think I've sorted this out in #985, where it was easier for me to start fresh with a new branch than rebase and reuse the old one in this PR.